/* automatically generated by rust-bindgen 0.72.1 */

pub type HighsInt = ::std::os::raw::c_int;
pub type HighsUInt = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HighsCallbackDataOut {
    pub cbdata: *mut ::std::os::raw::c_void,
    pub log_type: ::std::os::raw::c_int,
    pub running_time: f64,
    pub simplex_iteration_count: HighsInt,
    pub ipm_iteration_count: HighsInt,
    pub pdlp_iteration_count: HighsInt,
    pub objective_function_value: f64,
    pub mip_node_count: i64,
    pub mip_total_lp_iterations: i64,
    pub mip_primal_bound: f64,
    pub mip_dual_bound: f64,
    pub mip_gap: f64,
    pub mip_solution: *mut f64,
    pub mip_solution_size: HighsInt,
    pub cutpool_num_col: HighsInt,
    pub cutpool_num_cut: HighsInt,
    pub cutpool_num_nz: HighsInt,
    pub cutpool_start: *mut HighsInt,
    pub cutpool_index: *mut HighsInt,
    pub cutpool_value: *mut f64,
    pub cutpool_lower: *mut f64,
    pub cutpool_upper: *mut f64,
    pub external_solution_query_origin: HighsInt,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of HighsCallbackDataOut"][::std::mem::size_of::<HighsCallbackDataOut>() - 160usize];
    ["Alignment of HighsCallbackDataOut"][::std::mem::align_of::<HighsCallbackDataOut>() - 8usize];
    ["Offset of field: HighsCallbackDataOut::cbdata"]
        [::std::mem::offset_of!(HighsCallbackDataOut, cbdata) - 0usize];
    ["Offset of field: HighsCallbackDataOut::log_type"]
        [::std::mem::offset_of!(HighsCallbackDataOut, log_type) - 8usize];
    ["Offset of field: HighsCallbackDataOut::running_time"]
        [::std::mem::offset_of!(HighsCallbackDataOut, running_time) - 16usize];
    ["Offset of field: HighsCallbackDataOut::simplex_iteration_count"]
        [::std::mem::offset_of!(HighsCallbackDataOut, simplex_iteration_count) - 24usize];
    ["Offset of field: HighsCallbackDataOut::ipm_iteration_count"]
        [::std::mem::offset_of!(HighsCallbackDataOut, ipm_iteration_count) - 28usize];
    ["Offset of field: HighsCallbackDataOut::pdlp_iteration_count"]
        [::std::mem::offset_of!(HighsCallbackDataOut, pdlp_iteration_count) - 32usize];
    ["Offset of field: HighsCallbackDataOut::objective_function_value"]
        [::std::mem::offset_of!(HighsCallbackDataOut, objective_function_value) - 40usize];
    ["Offset of field: HighsCallbackDataOut::mip_node_count"]
        [::std::mem::offset_of!(HighsCallbackDataOut, mip_node_count) - 48usize];
    ["Offset of field: HighsCallbackDataOut::mip_total_lp_iterations"]
        [::std::mem::offset_of!(HighsCallbackDataOut, mip_total_lp_iterations) - 56usize];
    ["Offset of field: HighsCallbackDataOut::mip_primal_bound"]
        [::std::mem::offset_of!(HighsCallbackDataOut, mip_primal_bound) - 64usize];
    ["Offset of field: HighsCallbackDataOut::mip_dual_bound"]
        [::std::mem::offset_of!(HighsCallbackDataOut, mip_dual_bound) - 72usize];
    ["Offset of field: HighsCallbackDataOut::mip_gap"]
        [::std::mem::offset_of!(HighsCallbackDataOut, mip_gap) - 80usize];
    ["Offset of field: HighsCallbackDataOut::mip_solution"]
        [::std::mem::offset_of!(HighsCallbackDataOut, mip_solution) - 88usize];
    ["Offset of field: HighsCallbackDataOut::mip_solution_size"]
        [::std::mem::offset_of!(HighsCallbackDataOut, mip_solution_size) - 96usize];
    ["Offset of field: HighsCallbackDataOut::cutpool_num_col"]
        [::std::mem::offset_of!(HighsCallbackDataOut, cutpool_num_col) - 100usize];
    ["Offset of field: HighsCallbackDataOut::cutpool_num_cut"]
        [::std::mem::offset_of!(HighsCallbackDataOut, cutpool_num_cut) - 104usize];
    ["Offset of field: HighsCallbackDataOut::cutpool_num_nz"]
        [::std::mem::offset_of!(HighsCallbackDataOut, cutpool_num_nz) - 108usize];
    ["Offset of field: HighsCallbackDataOut::cutpool_start"]
        [::std::mem::offset_of!(HighsCallbackDataOut, cutpool_start) - 112usize];
    ["Offset of field: HighsCallbackDataOut::cutpool_index"]
        [::std::mem::offset_of!(HighsCallbackDataOut, cutpool_index) - 120usize];
    ["Offset of field: HighsCallbackDataOut::cutpool_value"]
        [::std::mem::offset_of!(HighsCallbackDataOut, cutpool_value) - 128usize];
    ["Offset of field: HighsCallbackDataOut::cutpool_lower"]
        [::std::mem::offset_of!(HighsCallbackDataOut, cutpool_lower) - 136usize];
    ["Offset of field: HighsCallbackDataOut::cutpool_upper"]
        [::std::mem::offset_of!(HighsCallbackDataOut, cutpool_upper) - 144usize];
    ["Offset of field: HighsCallbackDataOut::external_solution_query_origin"]
        [::std::mem::offset_of!(HighsCallbackDataOut, external_solution_query_origin) - 152usize];
};
impl Default for HighsCallbackDataOut {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct HighsCallbackDataIn {
    pub user_interrupt: ::std::os::raw::c_int,
    pub user_solution: *mut f64,
    pub cbdata: *mut ::std::os::raw::c_void,
    pub user_has_solution: ::std::os::raw::c_int,
    pub user_solution_size: HighsInt,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of HighsCallbackDataIn"][::std::mem::size_of::<HighsCallbackDataIn>() - 32usize];
    ["Alignment of HighsCallbackDataIn"][::std::mem::align_of::<HighsCallbackDataIn>() - 8usize];
    ["Offset of field: HighsCallbackDataIn::user_interrupt"]
        [::std::mem::offset_of!(HighsCallbackDataIn, user_interrupt) - 0usize];
    ["Offset of field: HighsCallbackDataIn::user_solution"]
        [::std::mem::offset_of!(HighsCallbackDataIn, user_solution) - 8usize];
    ["Offset of field: HighsCallbackDataIn::cbdata"]
        [::std::mem::offset_of!(HighsCallbackDataIn, cbdata) - 16usize];
    ["Offset of field: HighsCallbackDataIn::user_has_solution"]
        [::std::mem::offset_of!(HighsCallbackDataIn, user_has_solution) - 24usize];
    ["Offset of field: HighsCallbackDataIn::user_solution_size"]
        [::std::mem::offset_of!(HighsCallbackDataIn, user_solution_size) - 28usize];
};
impl Default for HighsCallbackDataIn {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type HighsCCallbackType = ::std::option::Option<
    unsafe extern "C" fn(
        arg1: ::std::os::raw::c_int,
        arg2: *const ::std::os::raw::c_char,
        arg3: *const HighsCallbackDataOut,
        arg4: *mut HighsCallbackDataIn,
        arg5: *mut ::std::os::raw::c_void,
    ),
>;
pub const kHighsMaximumStringLength: HighsInt = 512;
pub const kHighsStatusError: HighsInt = -1;
pub const kHighsStatusOk: HighsInt = 0;
pub const kHighsStatusWarning: HighsInt = 1;
pub const kHighsVarTypeContinuous: HighsInt = 0;
pub const kHighsVarTypeInteger: HighsInt = 1;
pub const kHighsVarTypeSemiContinuous: HighsInt = 2;
pub const kHighsVarTypeSemiInteger: HighsInt = 3;
pub const kHighsVarTypeImplicitInteger: HighsInt = 4;
pub const kHighsOptionTypeBool: HighsInt = 0;
pub const kHighsOptionTypeInt: HighsInt = 1;
pub const kHighsOptionTypeDouble: HighsInt = 2;
pub const kHighsOptionTypeString: HighsInt = 3;
pub const kHighsInfoTypeInt64: HighsInt = -1;
pub const kHighsInfoTypeInt: HighsInt = 1;
pub const kHighsInfoTypeDouble: HighsInt = 2;
pub const kHighsObjSenseMinimize: HighsInt = 1;
pub const kHighsObjSenseMaximize: HighsInt = -1;
pub const kHighsMatrixFormatColwise: HighsInt = 1;
pub const kHighsMatrixFormatRowwise: HighsInt = 2;
pub const kHighsHessianFormatTriangular: HighsInt = 1;
pub const kHighsHessianFormatSquare: HighsInt = 2;
pub const kHighsSolutionStatusNone: HighsInt = 0;
pub const kHighsSolutionStatusInfeasible: HighsInt = 1;
pub const kHighsSolutionStatusFeasible: HighsInt = 2;
pub const kHighsBasisValidityInvalid: HighsInt = 0;
pub const kHighsBasisValidityValid: HighsInt = 1;
pub const kHighsPresolveStatusNotPresolved: HighsInt = -1;
pub const kHighsPresolveStatusNotReduced: HighsInt = 0;
pub const kHighsPresolveStatusInfeasible: HighsInt = 1;
pub const kHighsPresolveStatusUnboundedOrInfeasible: HighsInt = 2;
pub const kHighsPresolveStatusReduced: HighsInt = 3;
pub const kHighsPresolveStatusReducedToEmpty: HighsInt = 4;
pub const kHighsPresolveStatusTimeout: HighsInt = 5;
pub const kHighsPresolveStatusNullError: HighsInt = 6;
pub const kHighsPresolveStatusOptionsError: HighsInt = 7;
pub const kHighsPresolveStatusOutOfMemory: HighsInt = 8;
pub const kHighsModelStatusNotset: HighsInt = 0;
pub const kHighsModelStatusLoadError: HighsInt = 1;
pub const kHighsModelStatusModelError: HighsInt = 2;
pub const kHighsModelStatusPresolveError: HighsInt = 3;
pub const kHighsModelStatusSolveError: HighsInt = 4;
pub const kHighsModelStatusPostsolveError: HighsInt = 5;
pub const kHighsModelStatusModelEmpty: HighsInt = 6;
pub const kHighsModelStatusOptimal: HighsInt = 7;
pub const kHighsModelStatusInfeasible: HighsInt = 8;
pub const kHighsModelStatusUnboundedOrInfeasible: HighsInt = 9;
pub const kHighsModelStatusUnbounded: HighsInt = 10;
pub const kHighsModelStatusObjectiveBound: HighsInt = 11;
pub const kHighsModelStatusObjectiveTarget: HighsInt = 12;
pub const kHighsModelStatusTimeLimit: HighsInt = 13;
pub const kHighsModelStatusIterationLimit: HighsInt = 14;
pub const kHighsModelStatusUnknown: HighsInt = 15;
pub const kHighsModelStatusSolutionLimit: HighsInt = 16;
pub const kHighsModelStatusInterrupt: HighsInt = 17;
pub const kHighsBasisStatusLower: HighsInt = 0;
pub const kHighsBasisStatusBasic: HighsInt = 1;
pub const kHighsBasisStatusUpper: HighsInt = 2;
pub const kHighsBasisStatusZero: HighsInt = 3;
pub const kHighsBasisStatusNonbasic: HighsInt = 4;
pub const kHighsCallbackLogging: HighsInt = 0;
pub const kHighsCallbackSimplexInterrupt: HighsInt = 1;
pub const kHighsCallbackIpmInterrupt: HighsInt = 2;
pub const kHighsCallbackMipSolution: HighsInt = 3;
pub const kHighsCallbackMipImprovingSolution: HighsInt = 4;
pub const kHighsCallbackMipLogging: HighsInt = 5;
pub const kHighsCallbackMipInterrupt: HighsInt = 6;
pub const kHighsCallbackMipGetCutPool: HighsInt = 7;
pub const kHighsCallbackMipDefineLazyConstraints: HighsInt = 8;
pub const kHighsCallbackCallbackMipUserSolution: HighsInt = 9;
pub const kHighsCallbackDataOutLogTypeName: &[u8; 9] = b"log_type\0";
pub const kHighsCallbackDataOutRunningTimeName: &[u8; 13] = b"running_time\0";
pub const kHighsCallbackDataOutSimplexIterationCountName: &[u8; 24] = b"simplex_iteration_count\0";
pub const kHighsCallbackDataOutIpmIterationCountName: &[u8; 20] = b"ipm_iteration_count\0";
pub const kHighsCallbackDataOutPdlpIterationCountName: &[u8; 21] = b"pdlp_iteration_count\0";
pub const kHighsCallbackDataOutObjectiveFunctionValueName: &[u8; 25] =
    b"objective_function_value\0";
pub const kHighsCallbackDataOutMipNodeCountName: &[u8; 15] = b"mip_node_count\0";
pub const kHighsCallbackDataOutMipTotalLpIterationsName: &[u8; 24] = b"mip_total_lp_iterations\0";
pub const kHighsCallbackDataOutMipPrimalBoundName: &[u8; 17] = b"mip_primal_bound\0";
pub const kHighsCallbackDataOutMipDualBoundName: &[u8; 15] = b"mip_dual_bound\0";
pub const kHighsCallbackDataOutMipGapName: &[u8; 8] = b"mip_gap\0";
pub const kHighsCallbackDataOutMipSolutionName: &[u8; 13] = b"mip_solution\0";
pub const kHighsCallbackDataOutCutpoolNumColName: &[u8; 16] = b"cutpool_num_col\0";
pub const kHighsCallbackDataOutCutpoolNumCutName: &[u8; 16] = b"cutpool_num_cut\0";
pub const kHighsCallbackDataOutCutpoolNumNzName: &[u8; 15] = b"cutpool_num_nz\0";
pub const kHighsCallbackDataOutCutpoolStartName: &[u8; 14] = b"cutpool_start\0";
pub const kHighsCallbackDataOutCutpoolIndexName: &[u8; 14] = b"cutpool_index\0";
pub const kHighsCallbackDataOutCutpoolValueName: &[u8; 14] = b"cutpool_value\0";
pub const kHighsCallbackDataOutCutpoolLowerName: &[u8; 14] = b"cutpool_lower\0";
pub const kHighsCallbackDataOutCutpoolUpperName: &[u8; 14] = b"cutpool_upper\0";
pub const kHighsIisStrategyLight: HighsInt = 0;
pub const kHighsIisStrategyFromLpRowPriority: HighsInt = 6;
pub const kHighsIisStrategyFromLpColPriority: HighsInt = 14;
pub const kHighsIisBoundFree: HighsInt = 1;
pub const kHighsIisBoundLower: HighsInt = 2;
pub const kHighsIisBoundUpper: HighsInt = 3;
pub const kHighsIisBoundBoxed: HighsInt = 4;
pub const kHighsIisStatusNotInConflict: HighsInt = -1;
pub const kHighsIisStatusMaybeInConflict: HighsInt = 0;
pub const kHighsIisStatusInConflict: HighsInt = 1;
unsafe extern "C" {
    pub fn Highs_lpCall(
        num_col: HighsInt,
        num_row: HighsInt,
        num_nz: HighsInt,
        a_format: HighsInt,
        sense: HighsInt,
        offset: f64,
        col_cost: *const f64,
        col_lower: *const f64,
        col_upper: *const f64,
        row_lower: *const f64,
        row_upper: *const f64,
        a_start: *const HighsInt,
        a_index: *const HighsInt,
        a_value: *const f64,
        col_value: *mut f64,
        col_dual: *mut f64,
        row_value: *mut f64,
        row_dual: *mut f64,
        col_basis_status: *mut HighsInt,
        row_basis_status: *mut HighsInt,
        model_status: *mut HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_mipCall(
        num_col: HighsInt,
        num_row: HighsInt,
        num_nz: HighsInt,
        a_format: HighsInt,
        sense: HighsInt,
        offset: f64,
        col_cost: *const f64,
        col_lower: *const f64,
        col_upper: *const f64,
        row_lower: *const f64,
        row_upper: *const f64,
        a_start: *const HighsInt,
        a_index: *const HighsInt,
        a_value: *const f64,
        integrality: *const HighsInt,
        col_value: *mut f64,
        row_value: *mut f64,
        model_status: *mut HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_qpCall(
        num_col: HighsInt,
        num_row: HighsInt,
        num_nz: HighsInt,
        q_num_nz: HighsInt,
        a_format: HighsInt,
        q_format: HighsInt,
        sense: HighsInt,
        offset: f64,
        col_cost: *const f64,
        col_lower: *const f64,
        col_upper: *const f64,
        row_lower: *const f64,
        row_upper: *const f64,
        a_start: *const HighsInt,
        a_index: *const HighsInt,
        a_value: *const f64,
        q_start: *const HighsInt,
        q_index: *const HighsInt,
        q_value: *const f64,
        col_value: *mut f64,
        col_dual: *mut f64,
        row_value: *mut f64,
        row_dual: *mut f64,
        col_basis_status: *mut HighsInt,
        row_basis_status: *mut HighsInt,
        model_status: *mut HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_create() -> *mut ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn Highs_destroy(highs: *mut ::std::os::raw::c_void);
}
unsafe extern "C" {
    pub fn Highs_version() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn Highs_versionMajor() -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_versionMinor() -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_versionPatch() -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_githash() -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn Highs_readModel(
        highs: *mut ::std::os::raw::c_void,
        filename: *const ::std::os::raw::c_char,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_writeModel(
        highs: *mut ::std::os::raw::c_void,
        filename: *const ::std::os::raw::c_char,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_writePresolvedModel(
        highs: *mut ::std::os::raw::c_void,
        filename: *const ::std::os::raw::c_char,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_clear(highs: *mut ::std::os::raw::c_void) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_clearModel(highs: *mut ::std::os::raw::c_void) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_clearSolver(highs: *mut ::std::os::raw::c_void) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_presolve(highs: *mut ::std::os::raw::c_void) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_run(highs: *mut ::std::os::raw::c_void) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_postsolve(
        highs: *mut ::std::os::raw::c_void,
        col_value: *const f64,
        col_dual: *const f64,
        row_dual: *const f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_writeSolution(
        highs: *const ::std::os::raw::c_void,
        filename: *const ::std::os::raw::c_char,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_writeSolutionPretty(
        highs: *const ::std::os::raw::c_void,
        filename: *const ::std::os::raw::c_char,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_passLp(
        highs: *mut ::std::os::raw::c_void,
        num_col: HighsInt,
        num_row: HighsInt,
        num_nz: HighsInt,
        a_format: HighsInt,
        sense: HighsInt,
        offset: f64,
        col_cost: *const f64,
        col_lower: *const f64,
        col_upper: *const f64,
        row_lower: *const f64,
        row_upper: *const f64,
        a_start: *const HighsInt,
        a_index: *const HighsInt,
        a_value: *const f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_passMip(
        highs: *mut ::std::os::raw::c_void,
        num_col: HighsInt,
        num_row: HighsInt,
        num_nz: HighsInt,
        a_format: HighsInt,
        sense: HighsInt,
        offset: f64,
        col_cost: *const f64,
        col_lower: *const f64,
        col_upper: *const f64,
        row_lower: *const f64,
        row_upper: *const f64,
        a_start: *const HighsInt,
        a_index: *const HighsInt,
        a_value: *const f64,
        integrality: *const HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_passModel(
        highs: *mut ::std::os::raw::c_void,
        num_col: HighsInt,
        num_row: HighsInt,
        num_nz: HighsInt,
        q_num_nz: HighsInt,
        a_format: HighsInt,
        q_format: HighsInt,
        sense: HighsInt,
        offset: f64,
        col_cost: *const f64,
        col_lower: *const f64,
        col_upper: *const f64,
        row_lower: *const f64,
        row_upper: *const f64,
        a_start: *const HighsInt,
        a_index: *const HighsInt,
        a_value: *const f64,
        q_start: *const HighsInt,
        q_index: *const HighsInt,
        q_value: *const f64,
        integrality: *const HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_passHessian(
        highs: *mut ::std::os::raw::c_void,
        dim: HighsInt,
        num_nz: HighsInt,
        format: HighsInt,
        start: *const HighsInt,
        index: *const HighsInt,
        value: *const f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_passLinearObjectives(
        highs: *const ::std::os::raw::c_void,
        num_linear_objective: HighsInt,
        weight: *const f64,
        offset: *const f64,
        coefficients: *const f64,
        abs_tolerance: *const f64,
        rel_tolerance: *const f64,
        priority: *const HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_addLinearObjective(
        highs: *const ::std::os::raw::c_void,
        weight: f64,
        offset: f64,
        coefficients: *const f64,
        abs_tolerance: f64,
        rel_tolerance: f64,
        priority: HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_clearLinearObjectives(highs: *const ::std::os::raw::c_void) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_passRowName(
        highs: *const ::std::os::raw::c_void,
        row: HighsInt,
        name: *const ::std::os::raw::c_char,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_passColName(
        highs: *const ::std::os::raw::c_void,
        col: HighsInt,
        name: *const ::std::os::raw::c_char,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_passModelName(
        highs: *const ::std::os::raw::c_void,
        name: *const ::std::os::raw::c_char,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_readOptions(
        highs: *const ::std::os::raw::c_void,
        filename: *const ::std::os::raw::c_char,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_setBoolOptionValue(
        highs: *mut ::std::os::raw::c_void,
        option: *const ::std::os::raw::c_char,
        value: HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_setIntOptionValue(
        highs: *mut ::std::os::raw::c_void,
        option: *const ::std::os::raw::c_char,
        value: HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_setDoubleOptionValue(
        highs: *mut ::std::os::raw::c_void,
        option: *const ::std::os::raw::c_char,
        value: f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_setStringOptionValue(
        highs: *mut ::std::os::raw::c_void,
        option: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getBoolOptionValue(
        highs: *const ::std::os::raw::c_void,
        option: *const ::std::os::raw::c_char,
        value: *mut HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getIntOptionValue(
        highs: *const ::std::os::raw::c_void,
        option: *const ::std::os::raw::c_char,
        value: *mut HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getDoubleOptionValue(
        highs: *const ::std::os::raw::c_void,
        option: *const ::std::os::raw::c_char,
        value: *mut f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getStringOptionValue(
        highs: *const ::std::os::raw::c_void,
        option: *const ::std::os::raw::c_char,
        value: *mut ::std::os::raw::c_char,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getOptionType(
        highs: *const ::std::os::raw::c_void,
        option: *const ::std::os::raw::c_char,
        type_: *mut HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_resetOptions(highs: *mut ::std::os::raw::c_void) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_writeOptions(
        highs: *const ::std::os::raw::c_void,
        filename: *const ::std::os::raw::c_char,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_writeOptionsDeviations(
        highs: *const ::std::os::raw::c_void,
        filename: *const ::std::os::raw::c_char,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getNumOptions(highs: *const ::std::os::raw::c_void) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getOptionName(
        highs: *const ::std::os::raw::c_void,
        index: HighsInt,
        name: *mut *mut ::std::os::raw::c_char,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getBoolOptionValues(
        highs: *const ::std::os::raw::c_void,
        option: *const ::std::os::raw::c_char,
        current_value: *mut HighsInt,
        default_value: *mut HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getIntOptionValues(
        highs: *const ::std::os::raw::c_void,
        option: *const ::std::os::raw::c_char,
        current_value: *mut HighsInt,
        min_value: *mut HighsInt,
        max_value: *mut HighsInt,
        default_value: *mut HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getDoubleOptionValues(
        highs: *const ::std::os::raw::c_void,
        option: *const ::std::os::raw::c_char,
        current_value: *mut f64,
        min_value: *mut f64,
        max_value: *mut f64,
        default_value: *mut f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getStringOptionValues(
        highs: *const ::std::os::raw::c_void,
        option: *const ::std::os::raw::c_char,
        current_value: *mut ::std::os::raw::c_char,
        default_value: *mut ::std::os::raw::c_char,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getIntInfoValue(
        highs: *const ::std::os::raw::c_void,
        info: *const ::std::os::raw::c_char,
        value: *mut HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getDoubleInfoValue(
        highs: *const ::std::os::raw::c_void,
        info: *const ::std::os::raw::c_char,
        value: *mut f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getInt64InfoValue(
        highs: *const ::std::os::raw::c_void,
        info: *const ::std::os::raw::c_char,
        value: *mut i64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getInfoType(
        highs: *const ::std::os::raw::c_void,
        info: *const ::std::os::raw::c_char,
        type_: *mut HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getSolution(
        highs: *const ::std::os::raw::c_void,
        col_value: *mut f64,
        col_dual: *mut f64,
        row_value: *mut f64,
        row_dual: *mut f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getBasis(
        highs: *const ::std::os::raw::c_void,
        col_status: *mut HighsInt,
        row_status: *mut HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getModelStatus(highs: *const ::std::os::raw::c_void) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getDualRay(
        highs: *const ::std::os::raw::c_void,
        has_dual_ray: *mut HighsInt,
        dual_ray_value: *mut f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getDualUnboundednessDirection(
        highs: *const ::std::os::raw::c_void,
        has_dual_unboundedness_direction: *mut HighsInt,
        dual_unboundedness_direction_value: *mut f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getPrimalRay(
        highs: *const ::std::os::raw::c_void,
        has_primal_ray: *mut HighsInt,
        primal_ray_value: *mut f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getObjectiveValue(highs: *const ::std::os::raw::c_void) -> f64;
}
unsafe extern "C" {
    pub fn Highs_getBasicVariables(
        highs: *const ::std::os::raw::c_void,
        basic_variables: *mut HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getBasisInverseRow(
        highs: *const ::std::os::raw::c_void,
        row: HighsInt,
        row_vector: *mut f64,
        row_num_nz: *mut HighsInt,
        row_index: *mut HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getBasisInverseCol(
        highs: *const ::std::os::raw::c_void,
        col: HighsInt,
        col_vector: *mut f64,
        col_num_nz: *mut HighsInt,
        col_index: *mut HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getBasisSolve(
        highs: *const ::std::os::raw::c_void,
        rhs: *const f64,
        solution_vector: *mut f64,
        solution_num_nz: *mut HighsInt,
        solution_index: *mut HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getBasisTransposeSolve(
        highs: *const ::std::os::raw::c_void,
        rhs: *const f64,
        solution_vector: *mut f64,
        solution_nz: *mut HighsInt,
        solution_index: *mut HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getReducedRow(
        highs: *const ::std::os::raw::c_void,
        row: HighsInt,
        row_vector: *mut f64,
        row_num_nz: *mut HighsInt,
        row_index: *mut HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getReducedColumn(
        highs: *const ::std::os::raw::c_void,
        col: HighsInt,
        col_vector: *mut f64,
        col_num_nz: *mut HighsInt,
        col_index: *mut HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_setBasis(
        highs: *mut ::std::os::raw::c_void,
        col_status: *const HighsInt,
        row_status: *const HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_setLogicalBasis(highs: *mut ::std::os::raw::c_void) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_setSolution(
        highs: *mut ::std::os::raw::c_void,
        col_value: *const f64,
        row_value: *const f64,
        col_dual: *const f64,
        row_dual: *const f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_setSparseSolution(
        highs: *mut ::std::os::raw::c_void,
        num_entries: HighsInt,
        index: *const HighsInt,
        value: *const f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_setCallback(
        highs: *mut ::std::os::raw::c_void,
        user_callback: HighsCCallbackType,
        user_callback_data: *mut ::std::os::raw::c_void,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_startCallback(
        highs: *mut ::std::os::raw::c_void,
        callback_type: HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_stopCallback(
        highs: *mut ::std::os::raw::c_void,
        callback_type: HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getRunTime(highs: *const ::std::os::raw::c_void) -> f64;
}
unsafe extern "C" {
    pub fn Highs_zeroAllClocks(highs: *const ::std::os::raw::c_void) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_addCol(
        highs: *mut ::std::os::raw::c_void,
        cost: f64,
        lower: f64,
        upper: f64,
        num_new_nz: HighsInt,
        index: *const HighsInt,
        value: *const f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_addCols(
        highs: *mut ::std::os::raw::c_void,
        num_new_col: HighsInt,
        costs: *const f64,
        lower: *const f64,
        upper: *const f64,
        num_new_nz: HighsInt,
        starts: *const HighsInt,
        index: *const HighsInt,
        value: *const f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_addVar(highs: *mut ::std::os::raw::c_void, lower: f64, upper: f64) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_addVars(
        highs: *mut ::std::os::raw::c_void,
        num_new_var: HighsInt,
        lower: *const f64,
        upper: *const f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_addRow(
        highs: *mut ::std::os::raw::c_void,
        lower: f64,
        upper: f64,
        num_new_nz: HighsInt,
        index: *const HighsInt,
        value: *const f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_addRows(
        highs: *mut ::std::os::raw::c_void,
        num_new_row: HighsInt,
        lower: *const f64,
        upper: *const f64,
        num_new_nz: HighsInt,
        starts: *const HighsInt,
        index: *const HighsInt,
        value: *const f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_ensureColwise(highs: *mut ::std::os::raw::c_void) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_ensureRowwise(highs: *mut ::std::os::raw::c_void) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_changeObjectiveSense(
        highs: *mut ::std::os::raw::c_void,
        sense: HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_changeObjectiveOffset(highs: *mut ::std::os::raw::c_void, offset: f64)
    -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_changeColIntegrality(
        highs: *mut ::std::os::raw::c_void,
        col: HighsInt,
        integrality: HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_changeColsIntegralityByRange(
        highs: *mut ::std::os::raw::c_void,
        from_col: HighsInt,
        to_col: HighsInt,
        integrality: *const HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_changeColsIntegralityBySet(
        highs: *mut ::std::os::raw::c_void,
        num_set_entries: HighsInt,
        set: *const HighsInt,
        integrality: *const HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_changeColsIntegralityByMask(
        highs: *mut ::std::os::raw::c_void,
        mask: *const HighsInt,
        integrality: *const HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_clearIntegrality(highs: *mut ::std::os::raw::c_void) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_changeColCost(
        highs: *mut ::std::os::raw::c_void,
        col: HighsInt,
        cost: f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_changeColsCostByRange(
        highs: *mut ::std::os::raw::c_void,
        from_col: HighsInt,
        to_col: HighsInt,
        cost: *const f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_changeColsCostBySet(
        highs: *mut ::std::os::raw::c_void,
        num_set_entries: HighsInt,
        set: *const HighsInt,
        cost: *const f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_changeColsCostByMask(
        highs: *mut ::std::os::raw::c_void,
        mask: *const HighsInt,
        cost: *const f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_changeColBounds(
        highs: *mut ::std::os::raw::c_void,
        col: HighsInt,
        lower: f64,
        upper: f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_changeColsBoundsByRange(
        highs: *mut ::std::os::raw::c_void,
        from_col: HighsInt,
        to_col: HighsInt,
        lower: *const f64,
        upper: *const f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_changeColsBoundsBySet(
        highs: *mut ::std::os::raw::c_void,
        num_set_entries: HighsInt,
        set: *const HighsInt,
        lower: *const f64,
        upper: *const f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_changeColsBoundsByMask(
        highs: *mut ::std::os::raw::c_void,
        mask: *const HighsInt,
        lower: *const f64,
        upper: *const f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_changeRowBounds(
        highs: *mut ::std::os::raw::c_void,
        row: HighsInt,
        lower: f64,
        upper: f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_changeRowsBoundsByRange(
        highs: *mut ::std::os::raw::c_void,
        from_row: HighsInt,
        to_row: HighsInt,
        lower: *const f64,
        upper: *const f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_changeRowsBoundsBySet(
        highs: *mut ::std::os::raw::c_void,
        num_set_entries: HighsInt,
        set: *const HighsInt,
        lower: *const f64,
        upper: *const f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_changeRowsBoundsByMask(
        highs: *mut ::std::os::raw::c_void,
        mask: *const HighsInt,
        lower: *const f64,
        upper: *const f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_changeCoeff(
        highs: *mut ::std::os::raw::c_void,
        row: HighsInt,
        col: HighsInt,
        value: f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getObjectiveSense(
        highs: *const ::std::os::raw::c_void,
        sense: *mut HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getObjectiveOffset(
        highs: *const ::std::os::raw::c_void,
        offset: *mut f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getColsByRange(
        highs: *const ::std::os::raw::c_void,
        from_col: HighsInt,
        to_col: HighsInt,
        num_col: *mut HighsInt,
        costs: *mut f64,
        lower: *mut f64,
        upper: *mut f64,
        num_nz: *mut HighsInt,
        matrix_start: *mut HighsInt,
        matrix_index: *mut HighsInt,
        matrix_value: *mut f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getColsBySet(
        highs: *const ::std::os::raw::c_void,
        num_set_entries: HighsInt,
        set: *const HighsInt,
        num_col: *mut HighsInt,
        costs: *mut f64,
        lower: *mut f64,
        upper: *mut f64,
        num_nz: *mut HighsInt,
        matrix_start: *mut HighsInt,
        matrix_index: *mut HighsInt,
        matrix_value: *mut f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getColsByMask(
        highs: *const ::std::os::raw::c_void,
        mask: *const HighsInt,
        num_col: *mut HighsInt,
        costs: *mut f64,
        lower: *mut f64,
        upper: *mut f64,
        num_nz: *mut HighsInt,
        matrix_start: *mut HighsInt,
        matrix_index: *mut HighsInt,
        matrix_value: *mut f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getRowsByRange(
        highs: *const ::std::os::raw::c_void,
        from_row: HighsInt,
        to_row: HighsInt,
        num_row: *mut HighsInt,
        lower: *mut f64,
        upper: *mut f64,
        num_nz: *mut HighsInt,
        matrix_start: *mut HighsInt,
        matrix_index: *mut HighsInt,
        matrix_value: *mut f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getRowsBySet(
        highs: *const ::std::os::raw::c_void,
        num_set_entries: HighsInt,
        set: *const HighsInt,
        num_row: *mut HighsInt,
        lower: *mut f64,
        upper: *mut f64,
        num_nz: *mut HighsInt,
        matrix_start: *mut HighsInt,
        matrix_index: *mut HighsInt,
        matrix_value: *mut f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getRowsByMask(
        highs: *const ::std::os::raw::c_void,
        mask: *const HighsInt,
        num_row: *mut HighsInt,
        lower: *mut f64,
        upper: *mut f64,
        num_nz: *mut HighsInt,
        matrix_start: *mut HighsInt,
        matrix_index: *mut HighsInt,
        matrix_value: *mut f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getRowName(
        highs: *const ::std::os::raw::c_void,
        row: HighsInt,
        name: *mut ::std::os::raw::c_char,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getRowByName(
        highs: *const ::std::os::raw::c_void,
        name: *const ::std::os::raw::c_char,
        row: *mut HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getColName(
        highs: *const ::std::os::raw::c_void,
        col: HighsInt,
        name: *mut ::std::os::raw::c_char,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getColByName(
        highs: *const ::std::os::raw::c_void,
        name: *const ::std::os::raw::c_char,
        col: *mut HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getColIntegrality(
        highs: *const ::std::os::raw::c_void,
        col: HighsInt,
        integrality: *mut HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_deleteColsByRange(
        highs: *mut ::std::os::raw::c_void,
        from_col: HighsInt,
        to_col: HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_deleteColsBySet(
        highs: *mut ::std::os::raw::c_void,
        num_set_entries: HighsInt,
        set: *const HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_deleteColsByMask(
        highs: *mut ::std::os::raw::c_void,
        mask: *mut HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_deleteRowsByRange(
        highs: *mut ::std::os::raw::c_void,
        from_row: HighsInt,
        to_row: HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_deleteRowsBySet(
        highs: *mut ::std::os::raw::c_void,
        num_set_entries: HighsInt,
        set: *const HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_deleteRowsByMask(
        highs: *mut ::std::os::raw::c_void,
        mask: *mut HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_scaleCol(
        highs: *mut ::std::os::raw::c_void,
        col: HighsInt,
        scaleval: f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_scaleRow(
        highs: *mut ::std::os::raw::c_void,
        row: HighsInt,
        scaleval: f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getInfinity(highs: *const ::std::os::raw::c_void) -> f64;
}
unsafe extern "C" {
    pub fn Highs_getSizeofHighsInt(highs: *const ::std::os::raw::c_void) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getNumCol(highs: *const ::std::os::raw::c_void) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getNumRow(highs: *const ::std::os::raw::c_void) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getNumNz(highs: *const ::std::os::raw::c_void) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getHessianNumNz(highs: *const ::std::os::raw::c_void) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getPresolvedNumCol(highs: *const ::std::os::raw::c_void) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getPresolvedNumRow(highs: *const ::std::os::raw::c_void) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getPresolvedNumNz(highs: *const ::std::os::raw::c_void) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getModel(
        highs: *const ::std::os::raw::c_void,
        a_format: HighsInt,
        q_format: HighsInt,
        num_col: *mut HighsInt,
        num_row: *mut HighsInt,
        num_nz: *mut HighsInt,
        hessian_num_nz: *mut HighsInt,
        sense: *mut HighsInt,
        offset: *mut f64,
        col_cost: *mut f64,
        col_lower: *mut f64,
        col_upper: *mut f64,
        row_lower: *mut f64,
        row_upper: *mut f64,
        a_start: *mut HighsInt,
        a_index: *mut HighsInt,
        a_value: *mut f64,
        q_start: *mut HighsInt,
        q_index: *mut HighsInt,
        q_value: *mut f64,
        integrality: *mut HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getLp(
        highs: *const ::std::os::raw::c_void,
        a_format: HighsInt,
        num_col: *mut HighsInt,
        num_row: *mut HighsInt,
        num_nz: *mut HighsInt,
        sense: *mut HighsInt,
        offset: *mut f64,
        col_cost: *mut f64,
        col_lower: *mut f64,
        col_upper: *mut f64,
        row_lower: *mut f64,
        row_upper: *mut f64,
        a_start: *mut HighsInt,
        a_index: *mut HighsInt,
        a_value: *mut f64,
        integrality: *mut HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getPresolvedLp(
        highs: *const ::std::os::raw::c_void,
        a_format: HighsInt,
        num_col: *mut HighsInt,
        num_row: *mut HighsInt,
        num_nz: *mut HighsInt,
        sense: *mut HighsInt,
        offset: *mut f64,
        col_cost: *mut f64,
        col_lower: *mut f64,
        col_upper: *mut f64,
        row_lower: *mut f64,
        row_upper: *mut f64,
        a_start: *mut HighsInt,
        a_index: *mut HighsInt,
        a_value: *mut f64,
        integrality: *mut HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getPresolvedColName(
        highs: *const ::std::os::raw::c_void,
        col: HighsInt,
        name: *mut ::std::os::raw::c_char,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getPresolvedRowName(
        highs: *const ::std::os::raw::c_void,
        row: HighsInt,
        name: *mut ::std::os::raw::c_char,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getIisLp(
        highs: *const ::std::os::raw::c_void,
        a_format: HighsInt,
        num_col: *mut HighsInt,
        num_row: *mut HighsInt,
        num_nz: *mut HighsInt,
        sense: *mut HighsInt,
        offset: *mut f64,
        col_cost: *mut f64,
        col_lower: *mut f64,
        col_upper: *mut f64,
        row_lower: *mut f64,
        row_upper: *mut f64,
        a_start: *mut HighsInt,
        a_index: *mut HighsInt,
        a_value: *mut f64,
        integrality: *mut HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getFixedLp(
        highs: *const ::std::os::raw::c_void,
        a_format: HighsInt,
        num_col: *mut HighsInt,
        num_row: *mut HighsInt,
        num_nz: *mut HighsInt,
        sense: *mut HighsInt,
        offset: *mut f64,
        col_cost: *mut f64,
        col_lower: *mut f64,
        col_upper: *mut f64,
        row_lower: *mut f64,
        row_upper: *mut f64,
        a_start: *mut HighsInt,
        a_index: *mut HighsInt,
        a_value: *mut f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_crossover(
        highs: *mut ::std::os::raw::c_void,
        num_col: HighsInt,
        num_row: HighsInt,
        col_value: *const f64,
        col_dual: *const f64,
        row_dual: *const f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getRanging(
        highs: *mut ::std::os::raw::c_void,
        col_cost_up_value: *mut f64,
        col_cost_up_objective: *mut f64,
        col_cost_up_in_var: *mut HighsInt,
        col_cost_up_ou_var: *mut HighsInt,
        col_cost_dn_value: *mut f64,
        col_cost_dn_objective: *mut f64,
        col_cost_dn_in_var: *mut HighsInt,
        col_cost_dn_ou_var: *mut HighsInt,
        col_bound_up_value: *mut f64,
        col_bound_up_objective: *mut f64,
        col_bound_up_in_var: *mut HighsInt,
        col_bound_up_ou_var: *mut HighsInt,
        col_bound_dn_value: *mut f64,
        col_bound_dn_objective: *mut f64,
        col_bound_dn_in_var: *mut HighsInt,
        col_bound_dn_ou_var: *mut HighsInt,
        row_bound_up_value: *mut f64,
        row_bound_up_objective: *mut f64,
        row_bound_up_in_var: *mut HighsInt,
        row_bound_up_ou_var: *mut HighsInt,
        row_bound_dn_value: *mut f64,
        row_bound_dn_objective: *mut f64,
        row_bound_dn_in_var: *mut HighsInt,
        row_bound_dn_ou_var: *mut HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_feasibilityRelaxation(
        highs: *mut ::std::os::raw::c_void,
        global_lower_penalty: f64,
        global_upper_penalty: f64,
        global_rhs_penalty: f64,
        local_lower_penalty: *const f64,
        local_upper_penalty: *const f64,
        local_rhs_penalty: *const f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getIis(
        highs: *mut ::std::os::raw::c_void,
        iis_num_col: *mut HighsInt,
        iis_num_row: *mut HighsInt,
        col_index: *mut HighsInt,
        row_index: *mut HighsInt,
        col_bound: *mut HighsInt,
        row_bound: *mut HighsInt,
        col_status: *mut HighsInt,
        row_status: *mut HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_resetGlobalScheduler(blocking: HighsInt);
}
unsafe extern "C" {
    pub fn Highs_getCallbackDataOutItem(
        data_out: *const HighsCallbackDataOut,
        item_name: *const ::std::os::raw::c_char,
    ) -> *const ::std::os::raw::c_void;
}
unsafe extern "C" {
    pub fn Highs_setCallbackSolution(
        data_in: *mut HighsCallbackDataIn,
        num_entries: HighsInt,
        value: *const f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_setCallbackSparseSolution(
        data_in: *mut HighsCallbackDataIn,
        num_entries: HighsInt,
        index: *const HighsInt,
        value: *const f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_repairCallbackSolution(data_in: *mut HighsCallbackDataIn) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_call(
        num_col: HighsInt,
        num_row: HighsInt,
        num_nz: HighsInt,
        col_cost: *const f64,
        col_lower: *const f64,
        col_upper: *const f64,
        row_lower: *const f64,
        row_upper: *const f64,
        a_start: *const HighsInt,
        a_index: *const HighsInt,
        a_value: *const f64,
        col_value: *mut f64,
        col_dual: *mut f64,
        row_value: *mut f64,
        row_dual: *mut f64,
        col_basis_status: *mut HighsInt,
        row_basis_status: *mut HighsInt,
        model_status: *mut HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_runQuiet(highs: *mut ::std::os::raw::c_void) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_setHighsLogfile(
        highs: *mut ::std::os::raw::c_void,
        logfile: *const ::std::os::raw::c_void,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_setHighsOutput(
        highs: *mut ::std::os::raw::c_void,
        outputfile: *const ::std::os::raw::c_void,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getIterationCount(highs: *const ::std::os::raw::c_void) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getSimplexIterationCount(highs: *const ::std::os::raw::c_void) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_setHighsBoolOptionValue(
        highs: *mut ::std::os::raw::c_void,
        option: *const ::std::os::raw::c_char,
        value: HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_setHighsIntOptionValue(
        highs: *mut ::std::os::raw::c_void,
        option: *const ::std::os::raw::c_char,
        value: HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_setHighsDoubleOptionValue(
        highs: *mut ::std::os::raw::c_void,
        option: *const ::std::os::raw::c_char,
        value: f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_setHighsStringOptionValue(
        highs: *mut ::std::os::raw::c_void,
        option: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_setHighsOptionValue(
        highs: *mut ::std::os::raw::c_void,
        option: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getHighsBoolOptionValue(
        highs: *const ::std::os::raw::c_void,
        option: *const ::std::os::raw::c_char,
        value: *mut HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getHighsIntOptionValue(
        highs: *const ::std::os::raw::c_void,
        option: *const ::std::os::raw::c_char,
        value: *mut HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getHighsDoubleOptionValue(
        highs: *const ::std::os::raw::c_void,
        option: *const ::std::os::raw::c_char,
        value: *mut f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getHighsStringOptionValue(
        highs: *const ::std::os::raw::c_void,
        option: *const ::std::os::raw::c_char,
        value: *mut ::std::os::raw::c_char,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getHighsOptionType(
        highs: *const ::std::os::raw::c_void,
        option: *const ::std::os::raw::c_char,
        type_: *mut HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_resetHighsOptions(highs: *mut ::std::os::raw::c_void) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getHighsIntInfoValue(
        highs: *const ::std::os::raw::c_void,
        info: *const ::std::os::raw::c_char,
        value: *mut HighsInt,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getHighsDoubleInfoValue(
        highs: *const ::std::os::raw::c_void,
        info: *const ::std::os::raw::c_char,
        value: *mut f64,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getNumCols(highs: *const ::std::os::raw::c_void) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getNumRows(highs: *const ::std::os::raw::c_void) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getHighsInfinity(highs: *const ::std::os::raw::c_void) -> f64;
}
unsafe extern "C" {
    pub fn Highs_getHighsRunTime(highs: *const ::std::os::raw::c_void) -> f64;
}
unsafe extern "C" {
    pub fn Highs_setOptionValue(
        highs: *mut ::std::os::raw::c_void,
        option: *const ::std::os::raw::c_char,
        value: *const ::std::os::raw::c_char,
    ) -> HighsInt;
}
unsafe extern "C" {
    pub fn Highs_getScaledModelStatus(highs: *const ::std::os::raw::c_void) -> HighsInt;
}
