//! Raw FFI bindings to the [HiGHS](https://highs.dev) optimization solver C API.
//!
//! This crate is a thin, unsafe layer generated from `highs/interfaces/highs_c_api.h`.
//! Every `Highs_*` function and `kHighs*` constant of HiGHS 1.14 is exposed here.
//! For a safe, idiomatic interface use the `highs` crate, which re-exports this
//! module as `highs::ffi`.
//!
//! Bindings are generated by bindgen at build time (feature `run-bindgen`,
//! enabled by default). When that feature is disabled, the checked-in
//! `bindings_pregenerated.rs` is used instead; it is valid only for the default
//! `HIGHSINT64=OFF` build, where `HighsInt = i32`.
#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]
#![allow(clippy::all)]

#[cfg(feature = "run-bindgen")]
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

#[cfg(not(feature = "run-bindgen"))]
include!("bindings_pregenerated.rs");

/// The three C API return codes, for convenience.
pub const STATUS_ERROR: HighsInt = kHighsStatusError;
pub const STATUS_OK: HighsInt = kHighsStatusOk;
pub const STATUS_WARNING: HighsInt = kHighsStatusWarning;

#[cfg(test)]
mod tests {
    use super::*;
    use std::ffi::CStr;
    use std::os::raw::c_char;

    #[test]
    fn version_string_is_1_14() {
        unsafe {
            let v = Highs_version();
            assert!(!v.is_null());
            let s = CStr::from_ptr(v as *const c_char).to_str().unwrap();
            assert!(s.starts_with("1.14"), "unexpected version {s}");
        }
    }

    #[test]
    fn create_run_destroy_roundtrip() {
        // Minimal LP: min x s.t. x >= 1, 0 <= x. Optimal x = 1, obj = 1.
        unsafe {
            let h = Highs_create();
            assert!(!h.is_null());
            // silence solver output during tests
            let flag = std::ffi::CString::new("output_flag").unwrap();
            Highs_setBoolOptionValue(h, flag.as_ptr(), 0);

            let num_col: HighsInt = 1;
            let num_row: HighsInt = 1;
            let num_nz: HighsInt = 1;
            let col_cost = [1.0f64];
            let col_lower = [0.0f64];
            let col_upper = [1.0e30f64];
            let row_lower = [1.0f64];
            let row_upper = [1.0e30f64];
            let a_start = [0 as HighsInt];
            let a_index = [0 as HighsInt];
            let a_value = [1.0f64];

            let rc = Highs_passLp(
                h,
                num_col,
                num_row,
                num_nz,
                kHighsMatrixFormatColwise,
                kHighsObjSenseMinimize,
                0.0,
                col_cost.as_ptr(),
                col_lower.as_ptr(),
                col_upper.as_ptr(),
                row_lower.as_ptr(),
                row_upper.as_ptr(),
                a_start.as_ptr(),
                a_index.as_ptr(),
                a_value.as_ptr(),
            );
            assert_eq!(rc, kHighsStatusOk);

            let rc = Highs_run(h);
            assert_eq!(rc, kHighsStatusOk);
            assert_eq!(Highs_getModelStatus(h), kHighsModelStatusOptimal);

            let mut x = [0.0f64; 1];
            Highs_getSolution(
                h,
                x.as_mut_ptr(),
                std::ptr::null_mut(),
                std::ptr::null_mut(),
                std::ptr::null_mut(),
            );
            assert!((x[0] - 1.0).abs() < 1e-9, "x = {}", x[0]);

            Highs_destroy(h);
        }
    }
}
